package studentdbms;

import com.mysql.jdbc.Connection;
import com.mysql.jdbc.PreparedStatement;
import com.mysql.jdbc.ResultSet;
import com.mysql.jdbc.ResultSetMetaData;
import com.mysql.jdbc.Statement;
import java.awt.Color;
import java.awt.print.PrinterException;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.sql.SQLException;
import java.util.Vector;
import static javax.management.Query.lt;


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Omer Khan
 */
public class Admin_HomePage extends javax.swing.JFrame {
    boolean clicked = false;
    Connection sqlConn =null;
    PreparedStatement prt = null;
    ResultSet rs=null;
    
    
    /**
     * Creates new form HomePage
     */
    public Admin_HomePage() {
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        sfname = new javax.swing.JLabel();
        slname = new javax.swing.JLabel();
        Sfname = new javax.swing.JTextField();
        Slname = new javax.swing.JTextField();
        semail = new javax.swing.JTextField();
        sphone = new javax.swing.JTextField();
        stemail = new javax.swing.JLabel();
        stphone = new javax.swing.JLabel();
        stgender = new javax.swing.JLabel();
        label1 = new java.awt.Label();
        genderBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        semesterBox = new javax.swing.JComboBox<>();
        stdsave = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        stgetId = new javax.swing.JTextField();
        C451box = new javax.swing.JComboBox<>();
        M410box = new javax.swing.JComboBox<>();
        W131box = new javax.swing.JComboBox<>();
        C453box = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        dbedit = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        stdgpa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        studentsTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        admintodo = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        AdminNote = new javax.swing.JTextArea();
        addnewadmin = new javax.swing.JButton();
        deleteadmintodo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        stdmsg = new javax.swing.JTextArea();
        sendmsg = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        stdid = new javax.swing.JTextField();
        viewadmintodo = new javax.swing.JButton();
        dbexit = new javax.swing.JButton();
        dbprint = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        View = new javax.swing.JButton();
        studentDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 204));
        setForeground(new java.awt.Color(255, 255, 204));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 51));
        jLabel2.setText("Student Registration");

        sfname.setText("First name");

        slname.setText("Last name");

        semail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                semailActionPerformed(evt);
            }
        });

        sphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphoneActionPerformed(evt);
            }
        });

        stemail.setText("Email");

        stphone.setText("Phone");

        stgender.setText("Gender");

        label1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        label1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        label1.setForeground(new java.awt.Color(153, 0, 51));
        label1.setText("Please select classes");

        genderBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Female", "Male", "Unknown" }));
        genderBox.setSelectedIndex(-1);
        genderBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("GPA");

        jLabel3.setText("Semester");

        semesterBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SPRING 2022", "FALL 2022", "SPRING 2023", "FALL 2023" }));
        semesterBox.setSelectedIndex(-1);

        stdsave.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        stdsave.setText("Add");
        stdsave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdsaveActionPerformed(evt);
            }
        });

        jLabel6.setText("Student ID");

        C451box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        C451box.setSelectedIndex(-1);

        M410box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        M410box.setSelectedIndex(-1);

        W131box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        W131box.setSelectedIndex(-1);

        C453box.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "No" }));
        C453box.setSelectedIndex(-1);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("INFO-C451");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("HIM-M410");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("ENG-W131");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("INFO-C453");

        dbedit.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        dbedit.setText("Update");
        dbedit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbeditActionPerformed(evt);
            }
        });

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Indiana_University_5_30.png"))); // NOI18N

        stdgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stdgpaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(69, 69, 69)
                        .addComponent(C451box, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(sfname)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3)
                                        .addComponent(slname, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(stemail, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stphone, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(stgender, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(stdgpa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(genderBox, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sphone, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(semail, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Slname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Sfname, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(stgetId)
                            .addComponent(semesterBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(65, 65, 65)
                        .addComponent(C453box, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(stdsave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dbedit))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(W131box, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(24, 24, 24)
                        .addComponent(M410box, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(42, 42, 42))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stgetId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Sfname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sfname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Slname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(slname))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stphone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(genderBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stgender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(stdgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(semesterBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(C451box, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(C453box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(M410box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel10)
                    .addComponent(W131box, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stdsave)
                    .addComponent(dbedit))
                .addContainerGap())
        );

        studentsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Email", "Phone", "Gender", "GPA", "Semester", "INFO-C451", "INFO-C453", "HIM-M410", "ENG-W131"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        studentsTable.getTableHeader().setReorderingAllowed(false);
        studentsTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(studentsTable);
        if (studentsTable.getColumnModel().getColumnCount() > 0) {
            studentsTable.getColumnModel().getColumn(0).setResizable(false);
            studentsTable.getColumnModel().getColumn(1).setResizable(false);
            studentsTable.getColumnModel().getColumn(2).setResizable(false);
            studentsTable.getColumnModel().getColumn(3).setResizable(false);
            studentsTable.getColumnModel().getColumn(4).setResizable(false);
            studentsTable.getColumnModel().getColumn(5).setResizable(false);
            studentsTable.getColumnModel().getColumn(6).setResizable(false);
            studentsTable.getColumnModel().getColumn(7).setResizable(false);
            studentsTable.getColumnModel().getColumn(8).setResizable(false);
            studentsTable.getColumnModel().getColumn(9).setResizable(false);
            studentsTable.getColumnModel().getColumn(10).setResizable(false);
            studentsTable.getColumnModel().getColumn(11).setResizable(false);
        }

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        admintodo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Task"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        admintodo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                admintodoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(admintodo);
        if (admintodo.getColumnModel().getColumnCount() > 0) {
            admintodo.getColumnModel().getColumn(0).setResizable(false);
            admintodo.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("To-Do List");

        AdminNote.setColumns(20);
        AdminNote.setRows(5);
        jScrollPane4.setViewportView(AdminNote);

        addnewadmin.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        addnewadmin.setText("Add");
        addnewadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addnewadminActionPerformed(evt);
            }
        });

        deleteadmintodo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        deleteadmintodo.setText("Remove");
        deleteadmintodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteadmintodoActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 0));
        jLabel4.setText("Send a Message to a Student");

        stdmsg.setColumns(20);
        stdmsg.setRows(5);
        jScrollPane2.setViewportView(stdmsg);

        sendmsg.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        sendmsg.setText("Send");
        sendmsg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendmsgActionPerformed(evt);
            }
        });

        jLabel12.setText("Enter Student ID");

        stdid.setToolTipText("");
        stdid.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        viewadmintodo.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        viewadmintodo.setText("View");
        viewadmintodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewadmintodoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(157, 157, 157)
                        .addComponent(jLabel5)
                        .addGap(81, 81, 81))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(stdid))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(102, 102, 102)
                                .addComponent(sendmsg)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(122, 122, 122)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(addnewadmin, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(deleteadmintodo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(viewadmintodo))
                            .addComponent(jScrollPane4))
                        .addGap(18, 18, 18)))
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(stdid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                .addGap(6, 6, 6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(addnewadmin)
                                .addComponent(viewadmintodo)
                                .addComponent(deleteadmintodo))
                            .addComponent(sendmsg)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        dbexit.setBackground(new java.awt.Color(51, 102, 255));
        dbexit.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dbexit.setForeground(new java.awt.Color(255, 255, 255));
        dbexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/sign-out.png"))); // NOI18N
        dbexit.setText("Log Out");
        dbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbexitActionPerformed(evt);
            }
        });

        dbprint.setBackground(new java.awt.Color(51, 102, 255));
        dbprint.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        dbprint.setForeground(new java.awt.Color(255, 255, 255));
        dbprint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/printer.png"))); // NOI18N
        dbprint.setText("Print");
        dbprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dbprintActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 0));
        jLabel7.setText("Student Management System");

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/pngwing.com.png"))); // NOI18N
        jLabel13.setText("jLabel13");

        View.setBackground(new java.awt.Color(51, 102, 255));
        View.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        View.setForeground(new java.awt.Color(255, 255, 255));
        View.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/view.png"))); // NOI18N
        View.setText("View");
        View.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewActionPerformed(evt);
            }
        });

        studentDelete.setBackground(new java.awt.Color(51, 102, 255));
        studentDelete.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        studentDelete.setForeground(new java.awt.Color(255, 255, 255));
        studentDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/delete.png"))); // NOI18N
        studentDelete.setText("Delete");
        studentDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(studentDelete)
                        .addGap(18, 18, 18)
                        .addComponent(View)
                        .addGap(18, 18, 18)
                        .addComponent(dbprint)
                        .addGap(18, 18, 18)
                        .addComponent(dbexit, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(262, 262, 262))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(studentDelete)
                                    .addComponent(View)
                                    .addComponent(dbprint)
                                    .addComponent(dbexit)
                                    .addComponent(jLabel7))
                                .addGap(274, 274, 274)))
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbexitActionPerformed
         int signout;
        signout = JOptionPane.showConfirmDialog(null,"Confirm Signout?",
            "Warning",JOptionPane.YES_NO_OPTION);
        if (signout ==JOptionPane.YES_OPTION ){                // TODO add your handling code here:
            dispose();
            UserSelection mainpage = new UserSelection();
            mainpage.show();
        }
    }//GEN-LAST:event_dbexitActionPerformed

    private void addnewadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addnewadminActionPerformed
        String adminnote = AdminNote.getText();// adminnote holds the task entered by the admin
        
        if("".equals(adminnote))
                {
                    JOptionPane.showMessageDialog(this,"Please enter a task first");
                }
        else{
            try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/todo?useSSL=false","root","");
            //Establishing a connection with MySQL database
            
            Statement stm = (Statement) con.createStatement();
            String query = "insert into todo (Task) values('"+adminnote+"')";
            // querying the database to enter the Admin Notes in the database
            stm.executeUpdate(query); //the database is updated here
            JOptionPane.showMessageDialog(null, "Task Added");
            AdminNote.setText("");
            }
           catch(Exception e){
            System.out.println(e);
        }
            
        }             // TODO add your handling code here:
    }//GEN-LAST:event_addnewadminActionPerformed

    private void deleteadmintodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteadmintodoActionPerformed
  
       
        if (admintodo.getSelectedRowCount() != 0)
        {
        try
        {
           DefaultTableModel model= (DefaultTableModel)admintodo.getModel(); //creating a table model from the admintodo table 
           int row = admintodo.getSelectedRow(); // saving the selected row in row which is used to delete from the interface
           
           String selected = model.getValueAt(row, 0).toString();
           
           String value = admintodo.getModel().getValueAt(row, 0).toString();
           
           int deleteItem;
                   deleteItem = JOptionPane.showConfirmDialog(null,"Are you sure you would like to delete this task?",
                   "Warning",JOptionPane.YES_NO_OPTION);
             if (deleteItem ==JOptionPane.YES_OPTION )
             {                
        
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/todo?useSSL=false","root","");
            
            Statement stm = (Statement) con.createStatement();
            String query = "delete from todo where tID ="+value+" ";
            stm.executeUpdate(query);
            
            JOptionPane.showMessageDialog(this,"Removed from todo-list");
            System.out.println(value);
            
            // setting the value of selected to the first value
            //running a for loop from zero since the table cannot have less than zero rows
            if (row >= 0) { 

                model.removeRow(row); // removing the selected row

                try {
                    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/todo?useSSL=false\",\"root\",\"\"");
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement("delete from todo where '"+selected+"' ");
                    ps.executeUpdate();
                }
                catch(Exception e){
            System.out.println(e);
        }           
            }
            
             }
          
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);
 
        }
        }
        else{
            JOptionPane.showMessageDialog(this,"No tasks selected");
        }
    }//GEN-LAST:event_deleteadmintodoActionPerformed

    private void ViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewActionPerformed
       /*
        This part of the code will display the current items in the database in
        case the admin does not want to enter any new students to the database
        They can simply click View to see the current students in the right side
        */
       if(clicked)      // This limits the click of the view button to one time.
           return;      // if it is allowed to run more than once it reprints the 
       clicked = true;  // database
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/students?useSSL=false","root","");
            Statement stm = (Statement) con.createStatement();
            String getdata = "select * from students";
            ResultSet rs = (ResultSet) stm.executeQuery(getdata); 
            while(rs.next())
            {
             String id = String.valueOf(rs.getInt("studentID"));
             String fname = rs.getString("FirstName");
             String lname = rs.getString("LastName");
             String email = rs.getString("Email");
             String ph = rs.getString("Phone");
             String gen = rs.getString("Gender");
             String grd = rs.getString("GPA");
             String cs1 = rs.getString("Semester");
             String cs2 = rs.getString("INFOC451");
             String cs3 = rs.getString("INFOC453");
             String cs4 = rs.getString("HIM410");
             String sem = rs.getString("English");
             
             String tbData[] = {id,fname,lname,email,ph, gen,grd,cs1,cs2,cs3,cs4,sem};
                DefaultTableModel df = (DefaultTableModel)studentsTable.getModel();
                df.addRow(tbData);
            }
       }
       catch(Exception e){
            System.out.println(e);
        }
           // TODO add your handling code here:
    }//GEN-LAST:event_ViewActionPerformed

    private void dbprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbprintActionPerformed
          try {
            boolean print = studentsTable.print();
            if (!print) {
                JOptionPane.showMessageDialog(null, "Printing Cancelled !!..");
            }
        } catch (PrinterException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_dbprintActionPerformed

    private void sendmsgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendmsgActionPerformed
          
            //This block of code sends the message from the admin screen
           // and uploads it to the messages table in the student database
           // it used the student id to identify which student the message is for
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/student?useSSL=false","root","");
            String studentmsg = (String)stdmsg.getText();
            String stid = (String)stdid.getText();
           // Statement stm = (Statement) con.createStatement();
           // String query = "insert into messages values('"+stid+"','"+studentmsg+"')";
            String query = "update messages set Message='"+studentmsg+"' where studentID='"+stid+"' ";
           //stm.executeUpdate(query);
           PreparedStatement ps = (PreparedStatement) con.prepareStatement(query);
           ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Message Sent!...");
            stdid.setText("");
            stdmsg.setText("");
            //
            //Student_homepage homepage = new Student_homepage();
            
            }
        catch(Exception e){
            System.out.println(e);
              }
            
    }//GEN-LAST:event_sendmsgActionPerformed

    private void stdsaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdsaveActionPerformed
        // TODO add your handling code here:
        //Code for reading and saving the data
        //entered in the Student Registration form
        //into the MySQL database
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/students?useSSL=false","root","");

            String StudentID = stgetId.getText();
            String FirstName = Sfname.getText();
            String LastName = Slname.getText();
            String Email = semail.getText();
            String Phone = sphone.getText();
            String Gender = (String)genderBox.getSelectedItem();
            String GPA = stdgpa.getText();
            String Semester = (String)semesterBox.getSelectedItem();
            String eng = (String)W131box.getSelectedItem();
            String c451 = (String)C451box.getSelectedItem();
            String c453= (String)C453box.getSelectedItem();
            String m410 = (String)M410box.getSelectedItem(); 
            
            
            if(" ".equals(StudentID)|| " ".equals(FirstName)|| " ".equals(LastName)|| " ".equals(Email)|| " ".equals(Phone)||genderBox.getSelectedItem() == null||" ".equals(GPA)||" ".equals(Semester)||W131box.getSelectedItem()==null || C451box.getSelectedItem()==null||C453box.getSelectedItem()==null||M410box.getSelectedItem()==null) {
                JOptionPane.showMessageDialog(this,"Plese fill out all required fields");
            }
            else{
            Statement stm = (Statement) con.createStatement();
            String query = "insert into students values('"+StudentID+"','"+FirstName+"','"+LastName+"','"+Email+"','"+Phone+"','"+Gender+"','"+GPA+"','"+Semester+"','"+c451+"','"+c453+"','"+m410+"','"+eng+"')";
            stm.executeUpdate(query);

            JOptionPane.showMessageDialog(this,"Student Added Successfully.");
            
            stgetId.setText("");
            Sfname.setText("");
            Slname.setText("");
            semail.setText("");
            sphone.setText("Enter without dashes");
            sphone.setForeground(new Color(150, 150, 150));
            genderBox.setSelectedIndex(-1);
            stdgpa.setText("");
            C451box.setSelectedIndex(-1);
            M410box.setSelectedIndex(-1);
            W131box.setSelectedIndex(-1);
            C453box.setSelectedIndex(-1);
            semesterBox.setSelectedIndex(-1);
            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(this,"Student already exists in the system");
            System.out.print(e);
        }
    }//GEN-LAST:event_stdsaveActionPerformed

    private void genderBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderBoxActionPerformed

    private void studentsTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsTableMouseClicked
        // TODO add your handling code here:
       DefaultTableModel RecordTable = (DefaultTableModel)studentsTable.getModel();
       int getRow = studentsTable.getSelectedRow();
      
            stgetId.setText(RecordTable.getValueAt (getRow, 0).toString());
            Sfname.setText(RecordTable.getValueAt (getRow, 1).toString());
            Slname.setText(RecordTable.getValueAt (getRow, 2).toString());
            semail.setText(RecordTable.getValueAt (getRow, 3).toString());
            sphone.setText(RecordTable.getValueAt (getRow, 4).toString());
            genderBox.setSelectedItem(RecordTable.getValueAt (getRow, 5).toString());
            stdgpa.setText(RecordTable.getValueAt (getRow, 6).toString());
            semesterBox.setSelectedItem(RecordTable.getValueAt (getRow, 7).toString());
            C451box.setSelectedItem(RecordTable.getValueAt (getRow, 8).toString());
            M410box.setSelectedItem(RecordTable.getValueAt (getRow, 9).toString());
            W131box.setSelectedItem(RecordTable.getValueAt (getRow, 10).toString());
            C453box.setSelectedItem(RecordTable.getValueAt (getRow, 11).toString());
       
    }//GEN-LAST:event_studentsTableMouseClicked

    private void dbeditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dbeditActionPerformed
       //This code is responsible for update a student's entry in the data base
       //It allows the user to update all the user data except the student ID
         try
        {
         
           Class.forName("com.mysql.jdbc.Driver"); 
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/students?useSSL=false","root","");
               PreparedStatement pst = (PreparedStatement) con.prepareStatement("update students set FirstName=?,LastName=?,"
                + "Email=?,Phone=?,Gender=?,GPA=?,Semester=?,INFOC451=?,INFOC453=?,HIM410=?,"
                + "English=? where studentId="+stgetId.getText()+" ");
            pst.setString(1, Sfname.getText());
            pst.setString(2, Slname.getText());
            pst.setString(3, semail.getText());
            pst.setString(4, sphone.getText());
            pst.setString(5, (String) genderBox.getSelectedItem());
            pst.setString(6, stdgpa.getText());
            pst.setString(7, (String)semesterBox.getSelectedItem());
            pst.setString(8, (String)C451box.getSelectedItem());
            pst.setString(9, (String)C453box.getSelectedItem());
            pst.setString(10, (String)M410box.getSelectedItem());
            pst.setString(11, (String)W131box.getSelectedItem());
            pst.executeUpdate();
            
            JOptionPane.showMessageDialog(this,"Student Record updated");
            
            stgetId.setText("");
            Sfname.setText("");
            Slname.setText("");
            semail.setText("");
            sphone.setText("");
            genderBox.setSelectedIndex(-1);
            stdgpa.setText("");
            C451box.setSelectedIndex(-1);
            M410box.setSelectedIndex(-1);
            W131box.setSelectedIndex(-1);
            C453box.setSelectedIndex(-1);
            semesterBox.setSelectedIndex(-1);
        }
        
        catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);

        } 
 
    }//GEN-LAST:event_dbeditActionPerformed

    private void studentDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentDeleteActionPerformed

        try
        {
           
          
           int deleteItem;
                   deleteItem = JOptionPane.showConfirmDialog(null,"Confirm if you want to delete item",
                   "Warning",JOptionPane.YES_NO_OPTION);
             if (deleteItem ==JOptionPane.YES_OPTION )
             {                
        
           Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/students?useSSL=false","root","");
            
            Statement stm = (Statement) con.createStatement();
            String query = "delete from students where studentID ="+stgetId.getText()+" ";
            stm.executeUpdate(query);
            JOptionPane.showMessageDialog(this,"Student Record Deleted");
        
            stgetId.setText("");
            Sfname.setText("");
            Slname.setText("");
            semail.setText("");
            sphone.setText("");
            genderBox.setSelectedIndex(-1);
            stdgpa.setText("");
            C451box.setSelectedIndex(-1);
            M410box.setSelectedIndex(-1);
            W131box.setSelectedIndex(-1);
            C453box.setSelectedIndex(-1);
            semesterBox.setSelectedIndex(-1);
             int row = studentsTable.getSelectedRow(); // saving the selected row in row
            
               DefaultTableModel model= (DefaultTableModel)studentsTable.getModel(); //creating a table model from the students table 

               String selected = model.getValueAt(row, 0).toString(); // setting the value of selected to the first value

         //running a for loop from zero since the table cannot have less than zero rows
            if (row >= 0) { 

                model.removeRow(row); // removing the selected row

                try {
                    Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/todo?useSSL=false\",\"root\",\"\"");
                    PreparedStatement ps = (PreparedStatement) conn.prepareStatement("delete from students where '"+selected+"' ");
                    ps.executeUpdate();
                }
                catch(Exception e){
            System.out.println(e);
                  }           
            }
            
             }
          
        }
        
        catch (ClassNotFoundException ex) {
   java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE,
           null, ex);
        } catch (SQLException ex) {
             System.err.println(ex);
 
        }        // TODO add your handling code here:
    }//GEN-LAST:event_studentDeleteActionPerformed

    private void admintodoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admintodoMouseClicked
   
    }//GEN-LAST:event_admintodoMouseClicked

    private void viewadmintodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewadmintodoActionPerformed
        
        if(clicked)      // This limits the click of the view button to one time.
           return;      // if it is allowed to run more than once it reprints the 
        clicked = true;  // database
               
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/todo?useSSL=false","root","");
            Statement stm = (Statement) con.createStatement();
            String getdata = "select * from todo";
            ResultSet viewdata = (ResultSet) stm.executeQuery(getdata); 
            while(viewdata.next())
            {
             String Task = viewdata.getString("Task");
             String ID = viewdata.getString("tID");
             String tbData[] = {ID,Task};
                DefaultTableModel df = (DefaultTableModel)admintodo.getModel();
                df.addRow(tbData);
            }
       }
       catch(Exception e){
            System.out.println(e);
        }        
    }//GEN-LAST:event_viewadmintodoActionPerformed

    private void stdgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stdgpaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stdgpaActionPerformed

    private void semailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_semailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_semailActionPerformed

    private void sphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphoneActionPerformed
    // TODO add your handling code here:
    }//GEN-LAST:event_sphoneActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_HomePage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_HomePage().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea AdminNote;
    private javax.swing.JComboBox<String> C451box;
    private javax.swing.JComboBox<String> C453box;
    private javax.swing.JComboBox<String> M410box;
    private javax.swing.JTextField Sfname;
    private javax.swing.JTextField Slname;
    private javax.swing.JButton View;
    private javax.swing.JComboBox<String> W131box;
    private javax.swing.JButton addnewadmin;
    private javax.swing.JTable admintodo;
    private javax.swing.JButton dbedit;
    private javax.swing.JButton dbexit;
    private javax.swing.JButton dbprint;
    private javax.swing.JButton deleteadmintodo;
    private javax.swing.JComboBox<String> genderBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private java.awt.Label label1;
    private javax.swing.JTextField semail;
    private javax.swing.JComboBox<String> semesterBox;
    private javax.swing.JButton sendmsg;
    private javax.swing.JLabel sfname;
    private javax.swing.JLabel slname;
    private javax.swing.JTextField sphone;
    private javax.swing.JTextField stdgpa;
    private javax.swing.JTextField stdid;
    private javax.swing.JTextArea stdmsg;
    private javax.swing.JButton stdsave;
    private javax.swing.JLabel stemail;
    private javax.swing.JLabel stgender;
    private javax.swing.JTextField stgetId;
    private javax.swing.JLabel stphone;
    private javax.swing.JButton studentDelete;
    private javax.swing.JTable studentsTable;
    private javax.swing.JButton viewadmintodo;
    // End of variables declaration//GEN-END:variables
}
